import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/query-provider";
import { ProductsProvider } from "@/contexts/products-context";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Commerce web app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="container">
        <div
          className={`${geistSans.variable} ${geistMono.variable} antialiased px-2 xl:px-24 mx-auto py-20 bg-stone-100 space-y-8 min-h-dvh`}
        >
          <QueryProvider>
            <Suspense>
              <ProductsProvider>
                {children}
                {modal}
              </ProductsProvider>
            </Suspense>
          </QueryProvider>
        </div>
      </body>
    </html>
  );
}
